import ZendeskSetupView from './ZendeskSetupView.jsx';
import './settings.css';

export default function SettingsView({ api, username, apiDocsUrl }) {
  const healthUrl = apiDocsUrl?.endsWith('/docs')
    ? `${apiDocsUrl.slice(0, -5)}/health`
    : null;

  return (
    <>
      <header className="page-heading settings-heading">
        <div>
          <p className="eyebrow">USER & INTEGRATIONS</p>
          <h1>Settings</h1>
          <p>
            Keep account details, developer tools and Zendesk integration controls in
            one place instead of mixing setup actions into the request workspace.
          </p>
        </div>
      </header>

      <section className="settings-summary-grid">
        <article className="panel settings-card">
          <p className="eyebrow">ACCOUNT</p>
          <div className="settings-user-row">
            <span className="settings-avatar" aria-hidden="true">
              {username.slice(0, 1).toUpperCase()}
            </span>
            <div>
              <h2>{username}</h2>
              <p className="muted">Signed in to the Royal Tyres IT Asset Portal</p>
            </div>
          </div>
          <div className="settings-detail-list">
            <div>
              <span>Authentication</span>
              <strong>HTTP Basic demo login</strong>
            </div>
            <div>
              <span>Browser storage</span>
              <strong>Credentials kept in memory only</strong>
            </div>
          </div>
        </article>

        <article className="panel settings-card">
          <p className="eyebrow">DEVELOPER TOOLS</p>
          <h2>API & diagnostics</h2>
          <p className="muted">
            Swagger is generated by FastAPI on the backend, so it opens as the API's own
            documentation page rather than pretending to be another React screen.
          </p>
          <div className="settings-action-stack">
            <a
              className="button primary"
              href={apiDocsUrl}
              target="_blank"
              rel="noreferrer"
            >
              Open Swagger API docs <span aria-hidden="true">↗</span>
            </a>
            {healthUrl && (
              <a
                className="button secondary"
                href={healthUrl}
                target="_blank"
                rel="noreferrer"
              >
                Open API health check <span aria-hidden="true">↗</span>
              </a>
            )}
          </div>
        </article>
      </section>

      <section className="settings-integration-heading">
        <p className="eyebrow">INTEGRATION</p>
        <h2>Zendesk push & status sync</h2>
        <p className="muted">
          Configure the Royal Tyres Zendesk objects, notification flow and authenticated
          status callback from here. Environment secrets remain in Render.
        </p>
      </section>

      <ZendeskSetupView api={api} embedded />
    </>
  );
}
